spring:
  # 동화 생성 테스트 때문에 아래 가짜 값으로 테스트 환경 설정
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: fake-client-id
            client-secret: fake-client-secret
            scope: name,email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  cloud:
    gcp:
      storage:
        credentials:
          location: dummy-location
        project-id: dummy-project
        bucket: dummy-bucket

  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}

  cookie:
    secure: false
    same-site: Lax